
from building import *
import rtconfig

cwd = GetCurrentDir()

src = []

if GetDepend(['BSP_USING_JPEG']):
    src += Glob('avifile.c')
    src += Glob('videoplayer.c')

CPPPATH = [cwd]
LOCAL_CFLAGS = ''

if rtconfig.PLATFORM in ['gcc', 'armclang']:
    LOCAL_CFLAGS += ' -std=c99'
elif rtconfig.PLATFORM in ['armcc']:
    LOCAL_CFLAGS += ' --c99'

group = DefineGroup('avi', src, depend = [], CPPPATH = CPPPATH, LOCAL_CFLAGS = LOCAL_CFLAGS)

Return('group')
